csv_name: breast_cancer.csv
dl_model_save_name: test_torchmlp_save.pth
feature_extraction: false
model: TorchMLP
model_save_name: model_save.pkl
models:
  CatBoost:
    depth: 8
    iterations: 222
    learning_rate: 0.1
    random_seed: 42
    verbose: false
  LogisticRegression:
    C: 1.0
    max_iter: 1000
    penalty: l2
    random_state: 42
    solver: lbfgs
  RandomForestClassifier:
    max_depth: 8
    n_estimators: 379
    random_state: 42
  SVM:
    C: 2.56
    kernel: linear
    probability: true
    random_state: 42
  TorchMLP:
    batch_size: 32
    epochs: 101
    hidden_dim: 10
    input_dim: 30
    learning_rate: 0.1037
    num_layers: 4
    output_dim: 1
  XGBoost:
    learning_rate: 0.1
    max_depth: 4
    n_estimators: 120
    random_state: 42
selectkbest: 82
target_col: diagnosis
test_size: 0.21
