target_col: diagnosis
csv_name: breast_cancer.csv
selectkbest: 142
models:
  RandomForestClassifier:
    n_estimators: 130
    max_depth: 4
    random_state: 42
    test_size: 0.2
  XGBoost:
    n_estimators: 107
    max_depth: 5
    learning_rate: 0.1
    random_state: 42
    test_size: 0.22
  LogisticRegression:
    penalty: l1
    C: 1.0
    solver: lbfgs
    max_iter: 1000
    random_state: 42
    test_size: 0.83
  SVM:
    kernel: rbf
    C: 3.83
    probability: true
    random_state: 42
    test_size: 0.72
  CatBoost:
    iterations: 100
    depth: 6
    learning_rate: 0.1
    random_seed: 42
    verbose: false
    test_size: 0.2
test_size: 0.2
model_save_name: breast_cancer_model.pkl
metrics:
- accuracy
- precision
- recall
- f1-score
model: SVM
