target_col: diagnosis
csv_name: breast_cancer.csv
selectkbest: 189
feature_extraction: false
models:
  RandomForestClassifier:
    n_estimators: 379
    max_depth: 8
    random_state: 42
    test_size: 0.2
  XGBoost:
    n_estimators: 436
    max_depth: 5
    learning_rate: 0.06
    random_state: 42
    test_size: 0.2
  LogisticRegression:
    penalty: l1
    C: 0.73
    solver: lbfgs
    max_iter: 1000
    random_state: 42
    test_size: 0.2
  SVM:
    kernel: linear
    C: 2.56
    probability: true
    random_state: 42
    test_size: 0.2
  CatBoost:
    iterations: 342
    depth: 8
    learning_rate: 0.1
    random_seed: 42
    verbose: false
    test_size: 0.2
test_size: 0.2
model_save_name: breast_cancer_model.pkl
metrics:
- accuracy
- precision
- recall
- f1-score
model: XGBoost
