target_col: diagnosis
csv_name: breast_cancer.csv
selectkbest: 109
feature_extraction: false
models:
  RandomForestClassifier:
    n_estimators: 379
    max_depth: 8
    random_state: 42
  XGBoost:
    n_estimators: 120
    max_depth: 4
    learning_rate: 0.09
    random_state: 42
  LogisticRegression:
    penalty: l2
    C: 1.0
    solver: lbfgs
    max_iter: 1000
    random_state: 42
  SVM:
    kernel: linear
    C: 2.56
    probability: true
    random_state: 42
  CatBoost:
    iterations: 222
    depth: 8
    learning_rate: 0.1
    random_seed: 42
    verbose: false
test_size: 0.23
model_save_name: breast_cancer_model.pkl
model: XGBoost
